[tox]
requires = tox-uv
envlist=
    lint
    py{310,311,312,313,314}-marshmallow{lowest,dev}
    mypy-marshmallowdev

[testenv]
runner = uv-venv-lock-runner
dependency_groups = tests
deps =
    marshmallowlowest: marshmallow==4.0.0
    marshmallowdev: https://github.com/marshmallow-code/marshmallow/archive/dev.tar.gz
commands = pytest {posargs}

[testenv:mypy-marshmallowdev]
dependency_groups =
    django
    mypy
deps =
    https://github.com/marshmallow-code/marshmallow/archive/dev.tar.gz
commands = mypy --warn-unused-ignores

[testenv:lint]
dependency_groups = lint
skip_install = true
commands = pre-commit run --all-files

; Below tasks are for development only (not run in CI)

[testenv:watch-readme]
runner = uv-venv-runner
deps = grip
skip_install = true
commands = grip -b
